/* ============================================================
   VAARAAHI — Menu Data
   Generated 1:1 from Menu_With_Rates.xlsx — every row of every
   sheet appears here exactly once. Only misspellings were fixed
   (Vujayawada -> Vijayawada, Panner -> Paneer, Schzwan ->
   Schezwan, etc.); no dish was renamed, merged, or dropped.

   p    = price          fam = family-pack price
   veg  = true/false     img = photo slug (see js/images.js)
   ============================================================ */

const MENU_CATEGORIES = [
  { id: "veg-app", label: "Veg Appetizers" },
  { id: "nonveg-app", label: "Non-Veg Appetizers" },
  { id: "veg-curry", label: "Veg Curries" },
  { id: "chicken-curry", label: "Chicken & Egg Curries" },
  { id: "goat-curry", label: "Goat Curries" },
  { id: "seafood-curry", label: "Seafood Curries" },
  { id: "breads", label: "Breads" },
  { id: "tandoori", label: "Tandoori Grill" },
  { id: "veg-biryani", label: "Veg Biryani & Pulao" },
  { id: "chk-biryani", label: "Chicken Biryani & Pulao" },
  { id: "goat-biryani", label: "Goat Biryani & Pulao" },
  { id: "sea-biryani", label: "Seafood Biryani" },
  { id: "fried-rice", label: "Fried Rice" },
  { id: "noodles", label: "Noodles" },
  { id: "kothu", label: "Kothu Parotta" },
  { id: "dessert", label: "Desserts" },
  { id: "drinks", label: "Drinks" },
];

const MENU_ITEMS = [
  /* ---- Veg Appetizers ---- */
  { c:"veg-app", n:"Mirchi Bajji (4 pcs)", p:6.49, veg:true, img:"mirchi-bajji" },
  { c:"veg-app", n:"Onion Pakoda", p:6.99, veg:true, img:"onion-pakoda" },
  { c:"veg-app", n:"Onion Samosa (4 pcs)", p:5.99, veg:true, img:"onion-samosa" },
  { c:"veg-app", n:"Punjabi Samosa (3 pcs)", p:5.99, veg:true, img:"punjabi-samosa" },
  { c:"veg-app", n:"Crispy Masala Pepper Corn", p:13.99, veg:true, img:"crispy-masala-pepper-corn" },
  { c:"veg-app", n:"Veg Cutlet", p:6.99, veg:true, img:"veg-cutlet", note:"Price set from comparable local menus" },
  { c:"veg-app", n:"Aloo Tikki (4 pcs)", p:5.99, veg:true, img:"aloo-tikki" },
  { c:"veg-app", n:"Karivepaku Paneer", p:13.99, veg:true, img:"karivepaku-paneer" },
  { c:"veg-app", n:"Karivepaku Gobi", p:12.99, veg:true, img:"karivepaku-gobi" },
  { c:"veg-app", n:"Karappodi Gobi", p:12.99, veg:true, img:"karappodi-gobi" },
  { c:"veg-app", n:"Gobi 65", p:12.99, veg:true, img:"gobi-65" },
  { c:"veg-app", n:"Gobi Manchurian", p:12.99, veg:true, img:"gobi-manchurian" },
  { c:"veg-app", n:"Veg Manchurian", p:12.99, veg:true, img:"veg-manchurian" },
  { c:"veg-app", n:"Babycorn Manchurian", p:12.99, veg:true, img:"babycorn-manchurian" },
  { c:"veg-app", n:"Paneer Manchurian", p:13.99, veg:true, img:"paneer-manchurian" },
  { c:"veg-app", n:"Chilli Paneer", p:13.99, veg:true, img:"chilli-paneer" },
  { c:"veg-app", n:"Water Chestnut Pepper Fry", p:12.99, veg:true, img:"water-chestnut-pepper-fry" },
  { c:"veg-app", n:"Mushroom Manchurian", p:12.99, veg:true, img:"mushroom-manchurian" },
  { c:"veg-app", n:"Mushroom Pepper Fry", p:12.99, veg:true, img:"mushroom-pepper-fry" },
  { c:"veg-app", n:"Chilli Mushroom", p:12.99, veg:true, img:"chilli-mushroom" },
  { c:"veg-app", n:"Nallakaram Gobi", p:12.99, veg:true, img:"nallakaram-gobi" },
  { c:"veg-app", n:"Nilgiri Gobi / Paneer", p:13.99, veg:true, img:"nilgiri-gobi-paneer" },
  { c:"veg-app", n:"Kaju Spinach Pakoda", p:12.99, veg:true, img:"kaju-spinach-pakoda" },
  { c:"veg-app", n:"Paneer 65", p:13.99, veg:true, img:"paneer-65" },
  { c:"veg-app", n:"Vegetable Momos", p:12.99, veg:true, img:"vegetable-momos" },
  { c:"veg-app", n:"Wok Fried Chilli Potato", p:9.99, veg:true, img:"wok-fried-chilli-potato" },
  { c:"veg-app", n:"Paneer Tikka Kebab", p:13.99, veg:true, img:"paneer-tikka-kebab" },
  { c:"veg-app", n:"Monagadu Gobi / Babycorn", p:12.99, veg:true, img:"monagadu-gobi-babycorn" },
  { c:"veg-app", n:"Pepper Fry Gobi / Babycorn", p:12.99, veg:true, img:"pepper-fry-gobi-babycorn" },
  { c:"veg-app", n:"Fire Babycorn / Paneer / Gobi", p:12.99, veg:true, img:"fire-babycorn-paneer-gobi" },
  { c:"veg-app", n:"777 (Paneer, Gobi, Babycorn, Mushroom)", p:13.99, veg:true, img:"777" },
  /* ---- Non-Veg Appetizers ---- */
  { c:"nonveg-app", n:"Charminar Chicken", p:13.99, veg:false, img:"charminar-chicken" },
  { c:"nonveg-app", n:"Chicken 777", p:13.99, veg:false, img:"chicken-777" },
  { c:"nonveg-app", n:"Chicken 65", p:13.99, veg:false, img:"chicken-65" },
  { c:"nonveg-app", n:"Chicken Lollipop (6 pcs)", p:13.99, veg:false, img:"chicken-lollipop" },
  { c:"nonveg-app", n:"Chicken Manchurian", p:13.99, veg:false, img:"chicken-manchurian" },
  { c:"nonveg-app", n:"Chilli Chicken", p:13.99, veg:false, img:"chilli-chicken" },
  { c:"nonveg-app", n:"Karivepaku Chicken", p:13.99, veg:false, img:"karivepaku-chicken" },
  { c:"nonveg-app", n:"Dhamaka Chicken", p:13.99, veg:false, img:"dhamaka-chicken" },
  { c:"nonveg-app", n:"Dhaba Chicken", p:13.99, veg:false, img:"dhaba-chicken" },
  { c:"nonveg-app", n:"Karaikudi Chicken Roast (Bone)", p:13.99, veg:false, img:"karaikudi-chicken-roast" },
  { c:"nonveg-app", n:"Rayalaseema Kodi Roast (Bone)", p:13.99, veg:false, img:"rayalaseema-kodi-roast" },
  { c:"nonveg-app", n:"Chicken Pepper Fry", p:13.99, veg:false, img:"chicken-pepper-fry" },
  { c:"nonveg-app", n:"Silk Chicken", p:13.99, veg:false, img:"silk-chicken" },
  { c:"nonveg-app", n:"Nallakaram Chicken", p:13.99, veg:false, img:"nallakaram-chicken" },
  { c:"nonveg-app", n:"Chicken Bone Fry", p:13.99, veg:false, img:"chicken-bone-fry" },
  { c:"nonveg-app", n:"Drums of Heaven (Chicken)", p:13.99, veg:false, img:"drums-of-heaven" },
  { c:"nonveg-app", n:"Nilgiri Chicken", p:13.99, veg:false, img:"nilgiri-chicken" },
  { c:"nonveg-app", n:"Japan Chicken", p:13.99, veg:false, img:"japan-chicken" },
  { c:"nonveg-app", n:"Fire Chicken", p:13.99, veg:false, img:"fire-chicken" },
  { c:"nonveg-app", n:"Chennai Chicken 65", p:13.99, veg:false, img:"chennai-chicken-65" },
  { c:"nonveg-app", n:"Chilli Fish / Shrimp", p:14.99, veg:false, img:"chilli-fish-shrimp" },
  { c:"nonveg-app", n:"Fish 777 / Shrimp", p:14.99, veg:false, img:"fish-777-shrimp" },
  { c:"nonveg-app", n:"Crispy Andhra Fried Fish", p:14.99, veg:false, img:"crispy-andhra-fried-fish" },
  { c:"nonveg-app", n:"Fish Pollichathu (Kerala Style)", p:14.99, veg:false, img:"fish-pollichathu" },
  { c:"nonveg-app", n:"Tawa Fish / Shrimp", p:14.99, veg:false, img:"tawa-fish-shrimp" },
  { c:"nonveg-app", n:"Nallakaram Fish / Shrimp", p:14.99, veg:false, img:"nallakaram-fish-shrimp" },
  { c:"nonveg-app", n:"Shrimp 65", p:14.99, veg:false, img:"shrimp-65" },
  { c:"nonveg-app", n:"Shrimp Pepper Fry", p:14.99, veg:false, img:"shrimp-pepper-fry" },
  { c:"nonveg-app", n:"Shrimp Manchurian", p:14.99, veg:false, img:"shrimp-manchurian" },
  { c:"nonveg-app", n:"Rayalaseema Royya Vepudu", p:14.99, veg:false, img:"rayalaseema-royya-vepudu" },
  { c:"nonveg-app", n:"Shrimp Dynamite", p:14.99, veg:false, img:"shrimp-dynamite" },
  { c:"nonveg-app", n:"Goat Sukka", p:16.99, veg:false, img:"goat-sukka" },
  { c:"nonveg-app", n:"Goat Chops", p:20.99, veg:false, img:"goat-chops" },
  /* ---- Veg Curries ---- */
  { c:"veg-curry", n:"Tadka Daal", p:11.99, veg:true, img:"tadka-daal" },
  { c:"veg-curry", n:"Spinach Daal", p:11.99, veg:true, img:"spinach-daal" },
  { c:"veg-curry", n:"Mango Daal", p:11.99, veg:true, img:"mango-daal" },
  { c:"veg-curry", n:"Aloo Gobi Masala", p:13.99, veg:true, img:"aloo-gobi-masala" },
  { c:"veg-curry", n:"Gutti Vankai Curry", p:13.99, veg:true, img:"gutti-vankai-curry" },
  { c:"veg-curry", n:"Punjabi Chana Masala", p:13.99, veg:true, img:"punjabi-chana-masala" },
  { c:"veg-curry", n:"Vegetable Tikka Masala", p:13.99, veg:true, img:"vegetable-tikka-masala" },
  { c:"veg-curry", n:"Kadai Paneer", p:14.99, veg:true, img:"kadai-paneer" },
  { c:"veg-curry", n:"Paneer Butter Masala", p:14.99, veg:true, img:"paneer-butter-masala" },
  { c:"veg-curry", n:"Paneer Tikka Masala", p:14.99, veg:true, img:"paneer-tikka-masala" },
  { c:"veg-curry", n:"Mutter Paneer", p:14.99, veg:true, img:"mutter-paneer" },
  { c:"veg-curry", n:"Palak Paneer", p:14.99, veg:true, img:"palak-paneer" },
  { c:"veg-curry", n:"Methi Chaman", p:13.99, veg:true, img:"methi-chaman" },
  { c:"veg-curry", n:"Nilgiri Paneer / Veg", p:14.99, veg:true, img:"nilgiri-paneer-veg" },
  { c:"veg-curry", n:"Navratan Korma", p:13.99, veg:true, img:"navratan-korma" },
  { c:"veg-curry", n:"Malai Kofta", p:13.99, veg:true, img:"malai-kofta" },
  { c:"veg-curry", n:"Vegetable Chettinad", p:13.99, veg:true, img:"vegetable-chettinad" },
  { c:"veg-curry", n:"Paneer Chettinad", p:14.99, veg:true, img:"paneer-chettinad" },
  { c:"veg-curry", n:"Shahi Paneer", p:14.99, veg:true, img:"shahi-paneer" },
  { c:"veg-curry", n:"Bhindi Masala", p:13.99, veg:true, img:"bhindi-masala" },
  { c:"veg-curry", n:"Malabar Veg Curry", p:13.99, veg:true, img:"malabar-veg-curry" },
  { c:"veg-curry", n:"Vegetable Salna", p:13.99, veg:true, img:"vegetable-salna" },
  { c:"veg-curry", n:"Andhra Veg Curry", p:13.99, veg:true, img:"andhra-veg-curry" },
  /* ---- Chicken & Egg Curries ---- */
  { c:"chicken-curry", n:"Egg Masala", p:12.99, veg:false, img:"egg-masala" },
  { c:"chicken-curry", n:"Egg Tikka Masala", p:12.99, veg:false, img:"egg-tikka-masala" },
  { c:"chicken-curry", n:"Butter Chicken", p:14.99, veg:false, img:"butter-chicken" },
  { c:"chicken-curry", n:"Chicken Tikka Masala", p:14.99, veg:false, img:"chicken-tikka-masala" },
  { c:"chicken-curry", n:"Chicken Chettinad", p:14.99, veg:false, img:"chicken-chettinad" },
  { c:"chicken-curry", n:"Chicken Korma", p:14.99, veg:false, img:"chicken-korma" },
  { c:"chicken-curry", n:"Gongura Chicken", p:14.99, veg:false, img:"gongura-chicken" },
  { c:"chicken-curry", n:"Chicken Vindaloo", p:14.99, veg:false, img:"chicken-vindaloo" },
  { c:"chicken-curry", n:"Kadai Chicken", p:14.99, veg:false, img:"kadai-chicken" },
  { c:"chicken-curry", n:"Methi Chicken", p:14.99, veg:false, img:"methi-chicken" },
  { c:"chicken-curry", n:"Kodi Vepudu (Semi Gravy)", p:14.99, veg:false, img:"kodi-vepudu" },
  { c:"chicken-curry", n:"Malabar Chicken", p:14.99, veg:false, img:"malabar-chicken" },
  { c:"chicken-curry", n:"Chicken Saagwala", p:14.99, veg:false, img:"chicken-saagwala" },
  { c:"chicken-curry", n:"Nilgiri Chicken Curry", p:14.99, veg:false, img:"nilgiri-chicken-curry" },
  { c:"chicken-curry", n:"Hyderabadi Murg Masala", p:14.99, veg:false, img:"hyderabadi-murg-masala" },
  { c:"chicken-curry", n:"Chicken Salna", p:14.99, veg:false, img:"chicken-salna" },
  { c:"chicken-curry", n:"Andhra Chicken Curry (Bone \u0026 Boneless)", p:14.99, veg:false, img:"andhra-chicken-curry" },
  /* ---- Goat Curries ---- */
  { c:"goat-curry", n:"Gongura Goat Curry", p:16.99, veg:false, img:"gongura-goat-curry" },
  { c:"goat-curry", n:"Andhra Special Goat Curry", p:16.99, veg:false, img:"andhra-special-goat-curry" },
  { c:"goat-curry", n:"Kadai Goat", p:16.99, veg:false, img:"kadai-goat" },
  { c:"goat-curry", n:"Goat Chettinad", p:16.99, veg:false, img:"goat-chettinad" },
  { c:"goat-curry", n:"Goat Vindaloo", p:16.99, veg:false, img:"goat-vindaloo" },
  { c:"goat-curry", n:"Nilgiri Goat", p:16.99, veg:false, img:"nilgiri-goat" },
  { c:"goat-curry", n:"Goat Korma", p:16.99, veg:false, img:"goat-korma" },
  { c:"goat-curry", n:"Mutton Masala", p:16.99, veg:false, img:"mutton-masala" },
  { c:"goat-curry", n:"Goat Saagwala", p:16.99, veg:false, img:"goat-saagwala" },
  { c:"goat-curry", n:"Goat Tikka Masala", p:16.99, veg:false, img:"goat-tikka-masala" },
  /* ---- Seafood Curries ---- */
  { c:"seafood-curry", n:"Malabar Fish / Shrimp Curry", p:16.99, veg:false, img:"malabar-fish-shrimp-curry" },
  { c:"seafood-curry", n:"Andhra Fish / Shrimp Curry", p:16.99, veg:false, img:"andhra-fish-shrimp-curry" },
  { c:"seafood-curry", n:"Nellore Chepala Pulusu", p:16.99, veg:false, img:"nellore-chepala-pulusu" },
  /* ---- Breads ---- */
  { c:"breads", n:"Naan", p:2.99, veg:true, img:"naan" },
  { c:"breads", n:"Butter Naan", p:2.99, veg:true, img:"butter-naan" },
  { c:"breads", n:"Garlic Naan", p:3.49, veg:true, img:"garlic-naan" },
  { c:"breads", n:"Onion Kulcha", p:4.99, veg:true, img:"onion-kulcha" },
  { c:"breads", n:"Cheese Kulcha", p:4.99, veg:true, img:"cheese-kulcha" },
  { c:"breads", n:"Bullet Naan", p:3.49, veg:true, img:"bullet-naan" },
  { c:"breads", n:"Sesame Naan", p:3.49, veg:true, img:"sesame-naan" },
  { c:"breads", n:"Roti", p:2.99, veg:true, img:"roti" },
  { c:"breads", n:"Butter Roti", p:2.99, veg:true, img:"butter-roti" },
  { c:"breads", n:"Chapathi", p:1.25, veg:true, img:"chapathi" },
  { c:"breads", n:"Puri", p:8.99, veg:true, img:"puri" },
  /* ---- Tandoori Grill ---- */
  { c:"tandoori", n:"Tandoori Chicken", p:10.99, sizes:["Half", "Full"], p2:19.99, veg:false, img:"tandoori-chicken" },
  { c:"tandoori", n:"Chicken Tikka Kebab", p:14.99, veg:false, img:"chicken-tikka-kebab" },
  { c:"tandoori", n:"Murg Malai Kebab", p:14.99, veg:false, img:"murg-malai-kebab" },
  { c:"tandoori", n:"Lasooni Chicken Kebab", p:14.99, veg:false, img:"lasooni-chicken-kebab" },
  { c:"tandoori", n:"Chicken Sheek Kebab", p:15.99, veg:false, img:"chicken-sheek-kebab" },
  { c:"tandoori", n:"Lamb Sheek Kebab", p:16.99, veg:false, img:"lamb-sheek-kebab" },
  { c:"tandoori", n:"Hariyali Chicken Kebab", p:14.99, veg:false, img:"hariyali-chicken-kebab" },
  { c:"tandoori", n:"Tangdi Kebab (6 pcs)", p:13.99, veg:false, img:"tangdi-kebab" },
  /* ---- Veg Biryani & Pulao ---- */
  { c:"veg-biryani", n:"Veg Dum Biryani", p:12.99, fam:27.99, veg:true, img:"veg-dum-biryani" },
  { c:"veg-biryani", n:"Vijayawada Veg Biryani", p:13.99, fam:28.99, veg:true, img:"vijayawada-veg" },
  { c:"veg-biryani", n:"Vijayawada Paneer Biryani", p:14.99, fam:29.99, veg:true, img:"vijayawada-paneer" },
  { c:"veg-biryani", n:"Paneer Fry Biryani", p:14.99, fam:29.99, veg:true, img:"paneer-fry-biryani" },
  { c:"veg-biryani", n:"Veg Keema Biryani / Pulao", p:13.99, fam:28.99, veg:true, img:"veg-keema-biryani-pulao" },
  { c:"veg-biryani", n:"Veg Roast Pulao", p:13.99, fam:28.99, veg:true, img:"veg-roast-pulao" },
  { c:"veg-biryani", n:"Gutti Vankai Biryani", p:13.99, fam:28.99, veg:true, img:"gutti-vankai-biryani" },
  { c:"veg-biryani", n:"Ulavacharu Veg / Paneer Biryani", p:14.99, fam:29.99, veg:true, img:"ulavacharu-veg-paneer" },
  { c:"veg-biryani", n:"Gongura Veg / Paneer Biryani", p:14.99, fam:29.99, veg:true, img:"gongura-veg-paneer" },
  { c:"veg-biryani", n:"Nilgiri Veg Biryani", p:13.99, fam:28.99, veg:true, img:"nilgiri-veg-biryani" },
  /* ---- Chicken Biryani & Pulao ---- */
  { c:"chk-biryani", n:"Chicken Dum Biryani", p:14.99, fam:29.99, veg:false, img:"chicken-dum-biryani" },
  { c:"chk-biryani", n:"Vijayawada Chicken Biryani (Boneless)", p:15.99, fam:30.99, veg:false, img:"vijayawada-chicken-biryani" },
  { c:"chk-biryani", n:"Rayalaseema Kodi Roast Chicken Biryani / Pulao", p:15.99, fam:30.99, veg:false, img:"rayalaseema-kodi-roast-chicken-biryani-pulao" },
  { c:"chk-biryani", n:"Ulavacharu Chicken Biryani / Pulao", p:15.99, fam:30.99, veg:false, img:"ulavacharu-chicken-biryani-pulao" },
  { c:"chk-biryani", n:"Gongura Chicken Biryani / Pulao", p:15.99, fam:30.99, veg:false, img:"gongura-chicken-biryani-pulao" },
  { c:"chk-biryani", n:"Avakai Chicken Biryani", p:15.99, fam:30.99, veg:false, img:"avakai-chicken-biryani" },
  { c:"chk-biryani", n:"Nilgiri Chicken Biryani", p:15.99, fam:30.99, veg:false, img:"nilgiri-chicken-biryani" },
  { c:"chk-biryani", n:"Egg Fry Pulao", p:14.99, fam:29.99, veg:false, img:"egg-fry-pulao" },
  { c:"chk-biryani", n:"Vijayawada Egg Biryani", p:14.99, fam:29.99, veg:false, img:"vijayawada-egg-biryani" },
  { c:"chk-biryani", n:"Bezawada Chicken Fry Piece Biryani", p:15.99, fam:30.99, veg:false, img:"bezawada-chickenn-fry-piece-biryani" },
  /* ---- Goat Biryani & Pulao ---- */
  { c:"goat-biryani", n:"Nalli Gosht Biryani", p:23.99, veg:false, img:"nalli-gosht-biryani" },
  { c:"goat-biryani", n:"Goat Dum Biryani", p:16.99, fam:33.99, veg:false, img:"goat-dum-biryani" },
  { c:"goat-biryani", n:"Goat Roast Pulao / Biryani", p:17.99, fam:34.99, veg:false, img:"goat-roast-pulao-biryani" },
  { c:"goat-biryani", n:"Gongura Mutton Biryani", p:17.99, fam:34.99, veg:false, img:"gongura-mutton-biryani" },
  { c:"goat-biryani", n:"Goat Keema Biryani / Pulao", p:17.99, fam:34.99, veg:false, img:"goat-keema-biryani-pulao" },
  { c:"goat-biryani", n:"Nilgiri Goat Biryani / Pulao", p:17.99, fam:34.99, veg:false, img:"nilgiri-goat-biryani-pulao" },
  { c:"goat-biryani", n:"Gongura Goat Kheema Biryani", p:18.99, fam:35.99, veg:false, img:"gongura-goat-kheema-biryani" },
  /* ---- Seafood Biryani ---- */
  { c:"sea-biryani", n:"Shrimp Biryani", p:15.99, fam:32.99, veg:false, img:"shrimp-biryani" },
  { c:"sea-biryani", n:"Shrimp Roast Pulao", p:16.99, fam:33.99, veg:false, img:"shrimp-roast-pulao" },
  { c:"sea-biryani", n:"Vijayawada Shrimp Biryani", p:16.99, fam:33.99, veg:false, img:"vijayawada-shrimp-biryani" },
  /* ---- Fried Rice ---- */
  { c:"fried-rice", n:"Street Style Veg Fried Rice", p:12.99, veg:true, img:"street-style-veg-fried-rice" },
  { c:"fried-rice", n:"Street Style Egg Fried Rice", p:13.99, veg:false, img:"street-style-egg-fried-rice" },
  { c:"fried-rice", n:"Street Style Chicken Fried Rice", p:14.99, veg:false, img:"street-style-chicken-fried-rice" },
  { c:"fried-rice", n:"Street Style Shrimp Fried Rice", p:15.99, veg:false, img:"street-style-shrimp-fried-rice" },
  { c:"fried-rice", n:"Schezwan Veg Fried Rice", p:13.49, veg:true, img:"schezwan-veg-fried-rice" },
  { c:"fried-rice", n:"Schezwan Egg Fried Rice", p:14.49, veg:false, img:"schezwan-egg-fried-rice" },
  { c:"fried-rice", n:"Schezwan Chicken Fried Rice", p:15.49, veg:false, img:"schezwan-chicken-fried-rice" },
  { c:"fried-rice", n:"Schezwan Shrimp Fried Rice", p:16.49, veg:false, img:"schezwan-shrimp-fried-rice" },
  /* ---- Noodles ---- */
  { c:"noodles", n:"Street Style Veg Noodles", p:12.99, veg:true, img:"street-style-veg-noodles" },
  { c:"noodles", n:"Street Style Egg Noodles", p:13.99, veg:false, img:"street-style-egg-noodles" },
  { c:"noodles", n:"Street Style Chicken Noodles", p:14.99, veg:false, img:"street-style-chicken-noodles" },
  { c:"noodles", n:"Street Style Shrimp Noodles", p:15.99, veg:false, img:"street-style-shrimp-noodles" },
  { c:"noodles", n:"Schezwan Veg Noodles", p:13.49, veg:true, img:"schezwan-veg-noodles" },
  { c:"noodles", n:"Schezwan Egg Noodles", p:14.49, veg:false, img:"schezwan-egg-noodles" },
  { c:"noodles", n:"Schezwan Chicken Noodles", p:15.49, veg:false, img:"schezwan-chicken-noodles" },
  { c:"noodles", n:"Schezwan Shrimp Noodles", p:16.49, veg:false, img:"schezwan-shrimp-noodles" },
  /* ---- Kothu Parotta ---- */
  { c:"kothu", n:"Malabar Paratha Veg Salna", p:12.99, veg:true, img:"malabar-paratha-veg-salna" },
  { c:"kothu", n:"Malabar Paratha Chicken Salna", p:13.99, veg:false, img:"malabar-paratha-chicken-salna" },
  { c:"kothu", n:"Kothu Parotta Veg", p:12.99, veg:true, img:"kothu-parotta-veg" },
  { c:"kothu", n:"Kothu Parotta Egg", p:13.99, veg:false, img:"kothu-parotta-egg" },
  { c:"kothu", n:"Kothu Parotta Chicken", p:14.99, veg:false, img:"kothu-parotta-chicken" },
  /* ---- Desserts ---- */
  { c:"dessert", n:"Rasmalai", p:5.99, veg:true, img:"rasmalai" },
  { c:"dessert", n:"Gulab Jamun with Rabdi", p:5.99, veg:true, img:"gulab-jamun-with-rabdi" },
  { c:"dessert", n:"Gulab Jamun", p:4.99, veg:true, img:"gulab-jamun" },
  { c:"dessert", n:"Double ka Meetha", p:5.99, veg:true, img:"double-ka-meetha" },
  { c:"dessert", n:"Apricot Delight", p:5.99, veg:true, img:"apricot-delight" },
  { c:"dessert", n:"Carrot Halwa", p:5.99, veg:true, img:"carrot-halwa" },
  { c:"dessert", n:"Paan", p:1.99, veg:true, img:"paan" },
  /* ---- Drinks ---- */
  { c:"drinks", n:"Tea", p:2.0, veg:true, img:"tea" },
  { c:"drinks", n:"Coffee", p:2.49, veg:true, img:"coffee" },
  { c:"drinks", n:"Mango Lassi", p:4.99, veg:true, img:"mango-lassi" },
  { c:"drinks", n:"Badam Milk", p:5.99, veg:true, img:"badam-milk" },
  { c:"drinks", n:"Beer", p:6.0, veg:true, img:"beer" },
];
